INSERT INTO "activities" VALUES (1, 'Sleeping in the lawn', 'On the sunny afternoon', 0.0, 0.0, 12.242, 12.242, 1);
INSERT INTO "activities" VALUES (2, 'Pick up a girl in the gym', 'Prepare your opener, and finger crossed ', 0.0, 0.0, 23.1242, 24.1252, 1);
INSERT INTO "activities" VALUES (3, 'Have a berry ice-cream boat', 'Yum Yum', 14.9, 14.9, -43.474188, 172.587959, 2);
INSERT INTO "activities" VALUES (4, 'Chill out in the berry garden', 'The perfect setting to enjoy a high tea with the girls, a lazy weekend brunch, a farm fresh lunch or a delicious berry dessert.', 10.0, 10.0, -43.4739667, 172.5873502, 2);
INSERT INTO "agent_trips" VALUES (1, 1);
INSERT INTO "agent_trips" VALUES (2, 2);
INSERT INTO "agents" VALUES (1, 'Cage');
INSERT INTO "agents" VALUES (2, 'Yoyo');
INSERT INTO "agents" VALUES (3, 'Eric');
INSERT INTO "bookings" VALUES (1, NULL, 1, 1);
INSERT INTO "bookings" VALUES (2, NULL, 2, 1);
INSERT INTO "bookings" VALUES (3, NULL, 3, 1);
INSERT INTO "bookings" VALUES (4, NULL, 1, 2);
INSERT INTO "bookings" VALUES (5, NULL, 2, 2);
INSERT INTO "companies" VALUES (1, 'University of Canterbury', 'Awesome Uni');
INSERT INTO "companies" VALUES (2, 'SweetHearts Restaurant', 'The restaurant is surrounded by fields of berries, expansive lawns and an old English garden');
INSERT INTO "customers" VALUES (1, 'Steve', 'Jobs', NULL, 'Male');
INSERT INTO "customers" VALUES (2, 'John', 'Appleseed', NULL, 'unisex');
INSERT INTO "trips" VALUES (1, '2014-04-01T00:00:00+00:00');
INSERT INTO "trips" VALUES (2, '2014-05-01T00:00:00+00:00');
